# fly.toml app configuration file generated for ctamap on 2026-03-22T03:33:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ctamap'
primary_region = 'ord'

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "15s"
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "5s"

[metrics]
  port = 8080
  path = "/metrics"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
