#!/usr/bin/env node
'use strict';
// Builds the LED board fonts from the source BDFs in scripts/fonts-src/
// (from hzeller/rpi-rgb-led-matrix/fonts) into server/board/fonts/.
//
//   node scripts/build-fonts.js
//
// Outputs (all BDF; the board build converts them to PCF):
//   board-small.bdf  Tom Thumb 3x5, proportional, + bolt, funnel, alert circle
//   board-5x7.bdf    X11 5x7, proportional, + "tt" ligature, "min" glyph
//   board-clock.bdf  X11 9x15 Bold, digits + square-dot colon (monospace)
//
// Rules (see docs/board/design-spec.md §3):
//   - Proportional: each glyph is trimmed to its ink columns, advance = ink + 1.
//   - Digits stay tabular (shared cell width) so rolling digits don't shift.
//   - Spaces: 2px small, 3px 5x7.
//   - Only printable ASCII is kept, plus the custom glyphs.

const fs = require('fs');
const path = require('path');
const { loadBDF, writeBDF } = require('../server/board/bdf');
const G = require('../server/board/glyphs');

const SRC = path.join(__dirname, 'fonts-src');
const OUT = path.join(__dirname, '..', 'server', 'board', 'fonts');

// ---- helpers ----

// Pixel art: array of strings, '#' = lit.
const art = (lines) => lines.map((l) => [...l].map((c) => (c === '#' ? 1 : 0)));

function glyph(name, code, rows, yoff, dw) {
  const w = rows[0].length;
  return { name, code, dw: dw != null ? dw : w + 1, bbx: [w, rows.length, 0, yoff], rows };
}

function inkCols(rows) {
  let lo = Infinity, hi = -1;
  for (const r of rows) r.forEach((b, c) => { if (b) { lo = Math.min(lo, c); hi = Math.max(hi, c); } });
  return hi < 0 ? null : [lo, hi];
}

// Trim a glyph to columns [lo, hi] and set its advance.
function trimCols(g, lo, hi, dw) {
  // Expand rows to full bbx width first (rows may be shorter than bbx w).
  const rows = g.rows.map((r) => {
    const full = [];
    for (let c = 0; c < g.bbx[0]; c++) full.push(r[c] || 0);
    // Shift by xoff so column indices are relative to the origin.
    return full;
  });
  const xo = g.bbx[2];
  const out = rows.map((r) => {
    const row = [];
    for (let c = lo; c <= hi; c++) row.push(r[c - xo] || 0);
    return row;
  });
  return { ...g, dw, bbx: [hi - lo + 1, g.bbx[1], 0, g.bbx[3]], rows: out };
}

// Ink columns in origin coordinates (accounts for xoff).
function inkRange(g) {
  const r = inkCols(g.rows);
  return r ? [r[0] + g.bbx[2], r[1] + g.bbx[2]] : null;
}

function makeProportional(font, spaceWidth) {
  const digits = [...'0123456789'].map((d) => font.glyphs.get(d.charCodeAt(0)));
  let dlo = Infinity, dhi = -1;
  for (const d of digits) { const r = inkRange(d); dlo = Math.min(dlo, r[0]); dhi = Math.max(dhi, r[1]); }

  for (const [code, g] of font.glyphs) {
    if (code === 32) {
      font.glyphs.set(code, { ...g, dw: spaceWidth, bbx: [1, 1, 0, 0], rows: [[0]] });
      continue;
    }
    if (code >= 0x30 && code <= 0x39) {
      font.glyphs.set(code, trimCols(g, dlo, dhi, dhi - dlo + 2));
      continue;
    }
    const r = inkRange(g);
    if (!r) continue;
    font.glyphs.set(code, trimCols(g, r[0], r[1], r[1] - r[0] + 2));
  }
}

function keepOnly(font, codes) {
  for (const code of [...font.glyphs.keys()]) if (!codes.has(code)) font.glyphs.delete(code);
}

const ascii = new Set(Array.from({ length: 95 }, (_, i) => 32 + i));

function setHeader(font, key, value) {
  const i = font.header.findIndex((l) => l.startsWith(key + ' '));
  const line = `${key} ${value}`;
  if (i >= 0) font.header[i] = line; else font.header.push(line);
}

function fixBoundingBox(font) {
  let minX = 0, minY = 0, maxX = 0, maxY = 0;
  for (const g of font.glyphs.values()) {
    const [w, h, xo, yo] = g.bbx;
    minX = Math.min(minX, xo); minY = Math.min(minY, yo);
    maxX = Math.max(maxX, xo + w); maxY = Math.max(maxY, yo + h);
  }
  setHeader(font, 'FONTBOUNDINGBOX', `${maxX - minX} ${maxY - minY} ${minX} ${minY}`);
}

function rename(font, family, note) {
  font.header = font.header.filter((l) => !l.startsWith('COMMENT'));
  font.header.splice(1, 0, `COMMENT ${note}`, 'COMMENT Generated by scripts/build-fonts.js. Do not edit; edit the script.');
  const fi = font.header.findIndex((l) => l.startsWith('FONT '));
  font.header[fi] = `FONT ${family}`;
  setHeader(font, 'SPACING', '"P"');
}

// ---- small: Tom Thumb ----

function buildSmall() {
  const f = loadBDF(path.join(SRC, 'tom-thumb.bdf'));
  keepOnly(f, ascii);
  makeProportional(f, 2);

  // W and w widened to 5px (stock 3px versions read as H and u).
  f.glyphs.set(87, glyph('W', 87, art([
    '#...#',
    '#...#',
    '#.#.#',
    '#.#.#',
    '.#.#.',
  ]), 0));
  f.glyphs.set(119, glyph('w', 119, art([
    '#...#',
    '#.#.#',
    '#.#.#',
    '.#.#.',
  ]), 0));

  // m widened to 5px with a 3-row x-height (the stock 3px m is a blob). Only
  // used as the chronological view's minutes suffix ("4m").
  f.glyphs.set(109, glyph('m', 109, art([
    '####.',
    '#.#.#',
    '#.#.#',
  ]), 0));

  // Degree sign, kept small: a 2x2 dot level with the top of the digits.
  f.glyphs.set(0xb0, glyph('degree', 0xb0, art([
    '##',
    '##',
  ]), 3));

  f.glyphs.set(G.BOLT, glyph('bolt', G.BOLT, art([
    '..#',
    '.#.',
    '###',
    '.#.',
    '#..',
  ]), 0));
  f.glyphs.set(G.FUNNEL, glyph('funnel', G.FUNNEL, art([
    '####',
    '.###',
    '.##.',
    '..#.',
    '.#..',
  ]), 0));
  // Alert circle: two layers drawn at the same origin, disc in red, mark in white.
  f.glyphs.set(G.ALERT_DISC, glyph('alert_disc', G.ALERT_DISC, art([
    '.#.#.',
    '##.##',
    '##.##',
    '#####',
    '.#.#.',
  ]), 0));
  f.glyphs.set(G.ALERT_MARK, glyph('alert_mark', G.ALERT_MARK, art([
    '..#..',
    '..#..',
    '..#..',
    '.....',
    '..#..',
  ]), 0));

  // Clock for schedule-based arrivals in the ticker index column (5px wide).
  f.glyphs.set(G.CLOCK, glyph('clock', G.CLOCK, art([
    '.###.',
    '#.#.#',
    '#.###',
    '#...#',
    '.###.',
  ]), 0));

  rename(f, '-ctamap-BoardSmall-Medium-R-Normal--6-60-75-75-P-40-ISO10646-1',
    'Board small font. Based on Tom Thumb by Robey Pointer (MIT license).');
  fixBoundingBox(f);
  return f;
}

// ---- 5x7 ----

function build5x7() {
  const f = loadBDF(path.join(SRC, '5x7.bdf'));
  keepOnly(f, ascii);
  makeProportional(f, 3);

  // 5x7 glyphs are 7 rows (yoff -1, bottom row is descent).
  f.glyphs.set(87, glyph('W', 87, art([
    '#...#',
    '#...#',
    '#...#',
    '#.#.#',
    '#.#.#',
    '.#.#.',
    '.....',
  ]), -1));
  f.glyphs.set(119, glyph('w', 119, art([
    '.....',
    '.....',
    '#...#',
    '#.#.#',
    '#.#.#',
    '.#.#.',
    '.....',
  ]), -1));
  // 0 widened from 3px to the 4px digit cell (the stock one is a skinny
  // diamond next to the 4px 8 and 6).
  f.glyphs.set(48, glyph('zero', 48, art([
    '.##.',
    '#..#',
    '#..#',
    '#..#',
    '#..#',
    '.##.',
    '....',
  ]), -1, 5));
  // t narrowed to 3px, bottom hook tucked under the crossbar.
  f.glyphs.set(116, glyph('t', 116, art([
    '.#.',
    '.#.',
    '###',
    '.#.',
    '.#.',
    '.##',
    '...',
  ]), -1));
  // "tt" ligature: two narrow t's sharing one crossbar.
  f.glyphs.set(G.TT, glyph('tt', G.TT, art([
    '.#..#.',
    '.#..#.',
    '######',
    '.#..#.',
    '.#..#.',
    '.##.##',
    '......',
  ]), -1));
  // "min": one 11px glyph with a 5-wide m.
  f.glyphs.set(G.MIN, glyph('min', G.MIN, art([
    '......#....',
    '...........',
    '##.#..#.##.',
    '#.#.#.#.#.#',
    '#.#.#.#.#.#',
    '#.#.#.#.#.#',
    '...........',
  ]), -1));

  rename(f, '-ctamap-Board5x7-Medium-R-Normal--7-70-75-75-P-50-ISO10646-1',
    'Board 5x7 font. Based on X11 misc-fixed 5x7 (public domain).');
  fixBoundingBox(f);
  return f;
}

// ---- clock: 9x15 Bold ----

function buildClock() {
  const f = loadBDF(path.join(SRC, '9x15B.bdf'));
  keepOnly(f, new Set([32, ...Array.from({ length: 10 }, (_, i) => 0x30 + i)]));

  // Digits occupy rows 2–11 of the 15-row cell (10px tall). The stock colon is
  // drawn for text and sits low; replace it with 2x2 square dots centered on
  // the digit height: rows 4–5 and 8–9 (2px from the top and bottom of the digits).
  const rows = Array.from({ length: 15 }, () => [0, 0]);
  for (const r of [4, 5, 8, 9]) rows[r] = [1, 1];
  f.glyphs.set(58, { name: 'colon', code: 58, dw: 4, bbx: [2, 15, 1, -3], rows });

  rename(f, '-ctamap-BoardClock-Bold-R-Normal--15-140-75-75-C-90-ISO10646-1',
    'Board clock font. Based on X11 misc-fixed 9x15 Bold (public domain).');
  setHeader(f, 'SPACING', '"C"');
  fixBoundingBox(f);
  return f;
}

// ---- main ----

fs.mkdirSync(OUT, { recursive: true });
const fonts = { 'board-small.bdf': buildSmall(), 'board-5x7.bdf': build5x7(), 'board-clock.bdf': buildClock() };
for (const [name, font] of Object.entries(fonts)) {
  fs.writeFileSync(path.join(OUT, name), writeBDF(font));
  console.log(`${name}: ${font.glyphs.size} glyphs`);
}
